### ISSUE TITLE
HTML render inverts Y axis

### ISSUE THREAD

**Issue by peabody124** [google/brax#100]
It appears there is an inconsistency in the coordinate conventions between Brax and Three.js. system.js partly handles this by swapping the Y-Z axes, but appears to leave the Y axis reversed. This can easily be seen with humanoid by raising one of the legs and comparing the outputs.

![Screen Shot 2021-11-04 at 9 09 24 AM](https://user-images.githubusercontent.com/618346/140328824-291c7f4d-61d8-4178-bbfb-56ca8e8fdf95.png)

I took a crack at modifying `system.js` but can't quite get things consistent. I'm pretty sure Y should be reversed here https://github.com/google/brax/blob/main/js/system.js#L146 but couldn't get the rotations consistent.

**Comment by justinberi** [comment]
I can confirm this. Using the config

```
bodies {
  name: "cart"
  colliders { box { halfsize { x: 0.05 y: 0.05 z: 0.05 } } }
  frozen { position { x:1 y:1 z:1 } rotation { x:1 y:1 z:1 } }
  inertia: {x: 1 y: 1 z: 1}
  mass: 1
}
bodies {
  name: "x"
  colliders { box { halfsize { x: 0.05 y: 0.05 z: 0.05 } } }
  frozen { position { x:1 y:1 z:1 } rotation { x:1 y:1 z:1 } }
  inertia: {x: 1 y: 1 z: 1}
  mass: 1
}
bodies {
  name: "y"
  colliders { capsule { radius: 0.1 length:0.1 } }
  frozen { position { x:1 y:1 z:1 } rotation { x:1 y:1 z:1 } }
  inertia: {x: 1 y: 1 z: 1}
  mass: 1
}
bodies {
  name: "z"
  colliders { box { halfsize { x: 0.1 y: 0.05 z: 0.05 } } }
  frozen { position { x:1 y:1 z:1 } rotation { x:1 y:1 z:1 } }
  inertia: {x: 1 y: 1 z: 1}
  mass: 1
}
defaults {
  qps { name: "cart" pos { x: 0 y: 0 z: 0} }
  qps { name: "x" pos { x: 1 y: 0 z: 0} }
  qps { name: "y" pos { x: 0 y: 1 z: 0} }
  qps { name: "z" pos { x: 0 y: 0 z: 1} }
}
collide_include {}
dt: 0.001
substeps: 0
```
Gives this in html
![image](https://user-images.githubusercontent.com/18635834/150062108-71235402-98cb-4bbf-a3a9-822138bd5444.png)

And this using the image renderer
![image](https://user-images.githubusercontent.com/18635834/150062129-cf8acb2a-d4d2-449a-98b9-a1d7496da5e8.png)

**Comment by justinberi** [comment]
It might make debugging easier if not conversion was made to a y-up frame. This would be tilted pi/2 radians in the html gui but the numbers reported would be one-to-one with what is coming out of brax and may make debugging easier.

**Comment by erikfrey** [comment]
Thanks all for pointing this out!  There was indeed a mirroring, which is now fixed in 3a197dba959901fab16333ccde7e44e8f1981cfd.  Closing, but please reach out if you still find any problems.

@justinberi yes the raw data in the html is in Brax's native z-up representation.  The one true representation    :-)   and we convert to three.js ' coordinate system in the javascript.

**Comment by peabody124** [comment]
Awesome thank you! (p.s. I haven't forgotten #99 I'm hoping to return to the project using the residual forces in the next week and will try and rebase it on the more recent changes)

**Comment by erikfrey** [comment]
@peabody124 no worries!  We actually went ahead and added external torque in 3a197dba959901fab16333ccde7e44e8f1981cfd - please let us know if you have any issues using it.
