### ISSUE TITLE
Force- or velocity-based actuators

### ISSUE THREAD

**Issue by RedTachyon** [google/brax#116]
From what I can tell, right now actuators can only work by applying a torque to a joint. Is there a sensible way of acting upon the bodies present in the scene by applying a force to them, or perhaps by directly setting their velocity instead?

**Comment by erikfrey** [comment]
Hi @RedTachyon , you can add linear forces through the act array by adding a Force to the config:

https://github.com/google/brax/blob/main/brax/physics/config.proto#L148

See inverted_pendulum for an example of how to use it:

https://github.com/google/brax/blob/main/brax/envs/inverted_pendulum.py

We will also soon add external torques too, see #99

**Comment by AlessandroZavoli** [comment]
This issue also relates to [Issue #163](https://github.com/google/brax/issues/163) : Aerodynamic forces/torques can be approximated as function of v squared

**Comment by erikfrey** [comment]
We now support both external linear force and torque inputs, as of 3a197dba959901fab16333ccde7e44e8f1981cfd.  Please try it out!  Closing this issue, but feel free to reach out with questions/bug reports/etc.
