### ISSUE TITLE
Checkerboard for floor object

### ISSUE THREAD

**Issue by benelot** [google/brax#133]
While training the swimmer I have a hard time to see if it even moves if I simulate a viable policy manually. Is there a way to enable a checkerboard floor texture to make this easier?

**Comment by benelot** [comment]
As Erwin tells me, there should be a grid on the ground, but it is not always visible (visible when looking top-down, but any other angle it is not there).

Suggestion: dont z buffer it or at least somehow in front of the floor object.

**Comment by erikfrey** [comment]
I was able to repro this on ubuntu chrome.  Poking around, I found a few related issues in three.js where the maintainers suggested it was some driver issue around drawing 1px width lines.

So I switched it to a checkerboard.  If your chrome is like mine, there is still a jitter that is impacting the texture and the shadow map texture - this doesn't show up on OSX chrome.  But at least now you can see movement - try it out!

**Comment by erikfrey** [comment]
Closing this as we've migrated to a checkerboard, but please reopen if anything else seems broken.
