### ISSUE TITLE
Unphysical behavior when using force thruster

### ISSUE THREAD

**Issue by fanheng123** [google/brax#154]
Hi, I'm trying to use force thruster to move a box body on which two other box body is attached via two joints. Weird behavior is observed when applying force on y direction. see link
[https://colab.research.google.com/drive/1L4lm8sAsXH8MoZLpNfKLe_aD7WN47AJd?usp=sharing](https://colab.research.google.com/drive/1L4lm8sAsXH8MoZLpNfKLe_aD7WN47AJd?usp=sharing)
applying force on x and z direction looks good. it feels issue only happens when the force is parallel to the joint axis.

**Comment by cdfreeman-google** [comment]
I think this is just an integration step size issue--everything works fine when I crank substeps up to `16`.  (dt of .05 is quite large, so 4 substeps isn't enough to ensure convergence)
