### ISSUE TITLE
Min action and max action

### ISSUE THREAD

**Issue by valentinmace** [google/brax#166]
Is it currently possible to get the min and max actions for a given environment ?

I want to clip the output actions of a policy to these bounds but I can't find how to do it.

Thanks in advance for your time.

**Comment by valentinmace** [comment]
By reading the GymWrapper I saw 
```
    action_high = jp.ones(self._env.action_size, dtype='float32')
    self.action_space = spaces.Box(-action_high, action_high, dtype='float32')
```
Which seems to indicate that high and low for actions are always respectively 1.0 and -1.0

**Comment by ikamensh** [comment]
Seems to be not the case for "halfcheetah".
