### ISSUE TITLE
'Brax Training with PyTorch on GPU' notebook fails to execute

### ISSUE THREAD

**Issue by BenGutteridge** [google/brax#185]
Due to a "can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first." error in pyplot, but fixing this raises another error.

**Comment by erikfrey** [comment]
Thanks for pointing this out.  Both errors are addressed in a660b273f21f305b2d86e440f532a300775835f5 and the colab  runs again.

**Comment by btaba** [comment]
Thanks for pointing this out @erwincoumans! I've fixed the brax.v2.positional import

**Comment by btaba** [comment]
Hi @erwincoumans @BenGutteridge , erikfrey pushed out a new pytorch colab recently https://colab.sandbox.google.com/github/google/brax/blob/main/notebooks/training_torch.ipynb
Just tested that it runs on GPU, sorry this took a while!
