### ISSUE TITLE
Joint of Reacher doesn't move

### ISSUE THREAD

**Issue by Markus28** [google/brax#191]
If we use Reacher in the provided notebook https://colab.research.google.com/github/google/brax/blob/main/notebooks/environments.ipynb the first joint doesn't move. Maybe I'm doing something wrong, but this looks like a bug to me.

**Comment by erikfrey** [comment]
@Markus28 yes indeed this is a bug!  We're looking into it now - thanks for the heads up.

**Comment by erikfrey** [comment]
Ah this wasn't a bug so much as the actuation signal I had chosen was canceling out the torques on the first joint.  I've updated the colab - if you rerun it with reacher you'll see both joints rotating now.

**Comment by btaba** [comment]
Thanks @Markus28  for reporting, closing the issue for now since reacher seems to work in the colab
