### ISSUE TITLE
box-box collisions unsupported

### ISSUE THREAD

**Issue by limbryan** [google/brax#206]
Hi,

I noticed the box-box collider pair is still unsupported. I was wondering this would be available anytime soon or can be easily addressed. Thanks!

**Comment by limbryan** [comment]
Hi @btaba, thanks for the quick response! Appreciate it! If I may ask, do you know when this is expected to be done?

**Comment by btaba** [comment]
Hi @limbryan, we don't have a good estimate at the moment but we're actively working on convex<>convex which would cover box<>box

**Comment by btaba** [comment]
We added an initial impl of box-box, we hope to expand on it and make it more performant in the future. Let us know if there are any bugs/issues!
