### ISSUE TITLE
how can we get depth with tinyrenderer?

### ISSUE THREAD

**Issue by aldopareja** [google/brax#223]
In physical environments, using depth makes inference over object properties a lot more reliable. Is there any hack to get depth from tinyrenderer?

**Comment by erikfrey** [comment]
Yes, you can fetch the depthbuffer from the return object:

https://github.com/erwincoumans/tinyrenderer/blob/master/python/pytinyrenderer.cc#L53

See here where we access the `rgb` field of the return object:

https://github.com/google/brax/blob/main/brax/io/image.py#L178

You could retrieve `depthbuffer` instead.  Have fun!

**Comment by aldopareja** [comment]
thank you so much!
