### ISSUE TITLE
update progress_fn to return params at each checkpoint

### ISSUE THREAD

**Issue by vijaysundaram** [google/brax#299]
Howdy Brax team! 

Can we update progress_fn arguments take and return params, in addition to metrics, at each checkpoint during training?

Yours,
Vijay

**Comment by erikfrey** [comment]
Just so we don't break existing APIs, we created a new function: `policy_params_fn` that will pass the make policy function, and params:

https://github.com/google/brax/blob/455e750f9354d986ef00523cb698cfe627979c9c/brax/training/agents/ppo/train.py#L87


This is live as of 455e750f9354d986ef00523cb698cfe627979c9c.  Enjoy!
