### ISSUE TITLE
Added walls to environment disappear in training

### ISSUE THREAD

**Issue by flobotics** [google/brax#32]
hi,
i build a custom env ( https://github.com/flobotics/brax/blob/main/brax/envs/simtoreal.py ) , which is mostly the reacher with walls around it. If i use html.render() it shows everything, but when i then go on with training and then look at the trajectory output, The walls start to sink into the ground and disappear ? I want to use the walls to let the target bounce off the walls , but if they are not there ?  What do i wrong ?

Here a images of the start of the trajectory video output:

![image](https://user-images.githubusercontent.com/11964445/129484962-2bec14a7-b721-471c-a189-3285e349e807.png)

Then it disappears

![image](https://user-images.githubusercontent.com/11964445/129484945-2551dc4c-3691-42dc-be08-bcfeb77a4dbd.png)

till its complety gone

![image](https://user-images.githubusercontent.com/11964445/129484990-6ae35eef-5802-4cbe-b306-475ca2efed51.png)

**Comment by flobotics** [comment]
adding frozen { all: true } to the wall bodies and they do not disappear anymore.  But when i now remove frozen { all: true } from the target-sphere-body,  so that the target-sphere-body can move around inside the walls, the target-sphere-body disappears in the trajectory-video-output ?

How can i use a sphere as a ball, jumping around and so ?

**Comment by flobotics** [comment]
i found that the ball is falling through the ground/plane at the beginnng of the trajectory video output ? I included 

```
collide_include {
    first: "ground"
    second: "ball"
}
collide_include {
    first: "ball"
    second: "ground"
}
```

But it still falls through ground ? How can i prevent that ?

![image](https://user-images.githubusercontent.com/11964445/129491485-fe886219-3398-4ce3-a861-22cc956b3f49.png)

**Comment by erikfrey** [comment]
Hello!  I think you have found a bug where brax doesn’t properly register the sphere collider.  As a workaround until we put in the proper fix, Can you try turning the ball into a sphere-shaped capsule where the length is double the radius?  See the `Object` body in `grasp.py` for an example.

**Comment by flobotics** [comment]
turning the ball from sphere into capsule like you said works, the ball bounces off the ground and rolls to the middle.

Perhaps the next bug is, that it seemed that all bodies or joints depend on ground-joint. I cannot describe it good, but if i lower only the parent_offset z value of the ground-arm_0-joint from 0.1 to 0.01 you see that also the walls and the new capsule-ball get lowered too, and sink into the ground ? But i only wanted to lower-down the arm_0 and arm_1 ?

![image](https://user-images.githubusercontent.com/11964445/129580987-66f92d41-9e98-4275-9571-8502bfcc1edf.png)

**Comment by erikfrey** [comment]
cc @cdfreeman-google 

Good timing for pointing this out.  Configs are missing an important piece of information which is to specify an initial offset for an unparented (is not the child of a joint) body.  Right now the system "guesses" where to put these unparented bodies and in your case, the guess is incorrect.

We are adding this new config now and will let you know when it's ready.  After it's done, you'll be able to specify different offsets for your walls vs the ball and arms, to put everything in its right place.

**Comment by flobotics** [comment]
i turned the boxes into capsule for the arms, but now the ball hits the ground, then rolls into the middle of the plane and then at the end one arm seemed to kick the ball out of the arena ?

Why are the arms not all the time hit the ball ?

A gif to watch is here: https://github.com/flobotics/brax/blob/main/out.gif

**Comment by erikfrey** [comment]
fyi, you can now specify initial positions for bodies in Brax, see for example this test:

https://github.com/google/brax/blob/main/brax/tests/physics_test.py#L128

Closing this issue, but please reach out if more problems remain.
