### ISSUE TITLE
Missing support to render cylinder

### ISSUE THREAD

**Issue by buzi-princeton** [google/brax#347]
`system.js` is missing support to render cylinder. Though we have support for capsules, in my experience replacing cylinder with capsule increases the number of contacts needed to be computed. Can we add support for cylinder?

**Comment by btaba** [comment]
Hi @buzi-princeton , you can always turn off contacts for whichever capsules get added, but we have a Cylinder PR that will be pushed out soon!

**Comment by btaba** [comment]
Cylinders are added in the latest push
