### ISSUE TITLE
autoreset batch environments when done=True

### ISSUE THREAD

**Issue by ludc** [google/brax#35]
Hi, and thanks for this amazing work.

I am wondering if there is a way to automatically reset an environment when reaching a terminal state when executing a batch of environments. It is unclear to me how to do this with BRAX when episodes can be of varying lengths.

**Comment by erikfrey** [comment]
@lebrice do you mean #43 ?  Yes, just addressed that too.

We now support this behavior (resetting batched environments automatically) by default.  If you're curious how it works, see `AutoResetWrapper` in https://github.com/google/brax/blob/main/brax/envs/wrappers.py

If you'd like the old behavior (which is to not auto-reset), you can still get it by calling `envs.create(..., auto_reset=False)`
