### ISSUE TITLE
In the reference xml files (e.g. `hopper.xml`) are all the custom options required

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [google/brax#351]
For example the `hopper.xml` 

https://github.com/google/brax/blob/main/brax/envs/assets/hopper.xml#L18

has options for springs, even though the model does not have

**Comment by btaba** [comment]
Hi @Kallinteris-Andreas those options are for the `positional` and `spring` backends, see 
https://github.com/google/brax/blob/c2cd14cf762242d63aeec106d955390c8e14d582/brax/base.py#L516-L521
