### ISSUE TITLE
can `Brax` simulate on the GPU (what args to use?)

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [google/brax#357]
Looking at the reference environments (e.g.) https://github.com/google/brax/blob/main/brax/envs/half_cheetah.py there is no device argument, it is possible to run the environment on a GPU or TPU?

Or did I read the README.md incorrectly

**Comment by erikfrey** [comment]
Hello, you can specify a default device in JAX or [specify it at time of jit](https://github.com/google/jax/issues/957).
