### ISSUE TITLE
little documentation about joints

### ISSUE THREAD

**Issue by flobotics** [google/brax#40]
hi,
i tried alot and i dont get it, perhaps its a bug. I dont know where the joint is placed and in which direction it can turn? For testing i use two boxes

![image](https://user-images.githubusercontent.com/11964445/130976697-c97933b3-431e-4272-888d-e7b4981b630c.png)

The code to test is here: https://github.com/flobotics/brax/blob/main/brax/envs/test_two_box_x_2.py

With a joint, that got no position{} values, so i think the joint is in the middle of both boxes, i can only rotate the boxes with rotation { y: -90}  no other value like z: 90,y: 0, x:90 work ?  Should not every value work ?

What does "rotation" mean ?

I know the example envs like halfcheetah which uses z:90 , but if i try to use that in a own config, it does not work ?

Also it seemed that the values for child_offset and parent_offset simply get added to the position values only of the child, so the joint-origin is always in the middle of the parent , is that correct ?

A little documentation about usage of joints would be nice 
thanks

**Comment by erikfrey** [comment]
Agree that this should be better laid out in our documentation - tracking this over at #112
