### ISSUE TITLE
Equality Constraints

### ISSUE THREAD

**Issue by brn-dev** [google/brax#419]
Does Brax have something similar to MuJoCos equality constraints (https://mujoco.readthedocs.io/en/latest/computation/index.html#equality) where two bodies can be welded together to suppress all relative degrees of freedom between them? If so, how would setting up such a constraint look?

**Comment by btaba** [comment]
Hi @brn-dev , Brax physics backends do not have equality constraints implemented, but they are implemented in https://github.com/google-deepmind/mujoco/tree/main/mjx currently
