### ISSUE TITLE
Load v1 configs in v2 for spring/positional backends

### ISSUE THREAD

**Issue by benjamin-macadam** [google/brax#430]
Hi there,

Related to my question in [https://github.com/google/brax/discussions/396](the discussion section), is there any way to load a config from the v1 format for the spring/positional backends? A way to translate that format to mujoco would be equally good.

**Comment by btaba** [comment]
You can use [`brax.v1`](https://github.com/google/brax/tree/main/brax/v1) 

For MJ format, use the current brax version
