### ISSUE TITLE
MjxEnv no where to be found

### ISSUE THREAD

**Issue by Engineering-Geek** [google/brax#451]
![image](https://github.com/google/brax/assets/64495110/fc0ab9e0-7b6f-4c1b-ae09-a68f7ac9e601)
As shown in the screen shot, MjxEnv is no longer detected anywhere in the code. I swear it was working earlier today on my PC...
When I open the file and looked through the code and current main branch, I can't find MjxEnv anywhere now unless if I am blind.

**Comment by btaba** [comment]
Hi @Engineering-Geek we just did a release and removed MjxEnv. You shouldn't need it anymore! If you'd like to work off of an older version of the code base, you can still use `0.9.4` via `pip install`

**Comment by btaba** [comment]
For more background info, you can use `PipelineEnv` now and add `backend='mjx'`, and use the MJX backend like any other backend in Brax
