### ISSUE TITLE
Broken links on Github's brax's main page

### ISSUE THREAD

**Issue by alex1yaremchuk** [google/brax#453]
Hi! 
I think it can be fixed that some links to colab demos are broken. 

F.i. this link https://github.com/google/brax/blob/main/brax/v2/positional/

here:
![image](https://github.com/google/brax/assets/40666786/0fac20ab-787d-4240-b5f9-c3230bc776ba)

Regards, 
Alexander

**Comment by btaba** [comment]
Thanks for the bug report! We'll fix the links :)

**Comment by btaba** [comment]
Fixed in 3c109cfd131e01691a53891e8f2ec9b32cf97670
