### ISSUE TITLE
`mjx.ncon` removed as of MuJoCo 3.1.5

### ISSUE THREAD

**Issue by namheegordonkim** [google/brax#485]
Hi friends,

It appears that MuJoCo officially removed `mjx.ncon` (https://mujoco.readthedocs.io/en/latest/changelog.html#version-3-1-5-may-7-2024) and hence this line is broken:

https://github.com/google/brax/blob/b45760cfa6ba0c3567ae36f988766a8299853c49/brax/contact.py#L38

Should be a quick fix; perhaps L38 should be replaced by

```
mujoco.MjData(sys.mj_model).ncon
```

or something cleverer.

**Comment by btaba** [comment]
Hi @namheegordonkim , we have a release in the backlog that we'll push out shortly! Apologies

**Comment by btaba** [comment]
See https://github.com/google/brax/releases/tag/v0.10.4 for the latest release. Thanks for the ping @namheegordonkim
