### ISSUE TITLE
Rendered Plane Texture Issue in Visualizer

### ISSUE THREAD

**Issue by bheijden** [google/brax#504]
The rendered plane in the visualizer is no longer showing the chequered pattern. It appears that the XML is ignoring the textures. Is this an intended change? Could you provide any information on which version introduced this change?

Below is the relevant XML code from `ant.xml`:
```xml
<asset>
  <texture builtin="gradient" height="100" rgb1="1 1 1" rgb2="0 0 0" type="skybox" width="100"/>
  <texture builtin="flat" height="1278" mark="cross" markrgb="1 1 1" name="texgeom" random="0.01" rgb1="0.8 0.6 0.4" rgb2="0.8 0.6 0.4" type="cube" width="127"/>
  <texture builtin="checker" height="100" name="texplane" rgb1="0 0 0" rgb2="0.8 0.8 0.8" type="2d" width="100"/>
  <material name="MatPlane" reflectance="0.5" shininess="1" specular="1" texrepeat="60 60" texture="texplane"/>
  <material name="geom" texture="texgeom" texuniform="true"/>
</asset>
<worldbody>
  <light cutoff="100" diffuse="1 1 1" dir="-0 0 -1.3" directional="true" exponent="1" pos="0 0 1.3" specular=".1 .1 .1"/>
  <geom conaffinity="1" condim="3" material="MatPlane" name="floor" pos="0 0 0" size="40 40 40" type="plane" rgba="0.5 0.5 0.5 1.0"/>
  ...
</worldbody>

```
And below the new vs old render produced by the visualizer in [this colab](https://colab.research.google.com/github/google/brax/blob/main/notebooks/training.ipynb):
![image](https://github.com/user-attachments/assets/379a0d41-a4ea-4d9c-a294-1d8bb1da52ba)
![image](https://github.com/user-attachments/assets/d73e3f38-1fed-4355-9139-1fcf854d062c)

**Comment by btaba** [comment]
See https://github.com/google/brax/releases/tag/v0.11.0, let us know if there's still an issue!
