### ISSUE TITLE
Friction per body?

### ISSUE THREAD

**Issue by namheegordonkim** [google/brax#55]
Hi,

I'm trying to create multiple bodies in the environment with differing friction coefficients. However, I couldn't find anywhere how to do this. It seems that most examples have a global friction coefficient of 0.6 but no difference across bodies.

I'd appreciate any thoughts on this. Thanks.

**Comment by erikfrey** [comment]
You're quite right - we only support friction for the whole scene.  Agreed it would be nice to have!

Adding per-collider friction in the config and plumbing it through would be a pretty small PR  I've marked it as a good issue for anyone who wants to help - otherwise we'll do this in one of the upcoming releases.

**Comment by namheegordonkim** [comment]
#59

**Comment by erwincoumans** [comment]
Thanks for the PR! Each body (collider) may have some friction (and restitution) coefficient. For a contact, the two friction coefficients often get combined to get a 'combined friction'. You may want to make it more clear in your PR.

**Comment by namheegordonkim** [comment]
@erwincoumans Aha, that makes sense.

> For a contact, the two friction coefficients often get combined to get a 'combined friction'.

Interesting. The global friction coefficient was the only thing being multiplied to impulse in `_collide()`: https://github.com/google/brax/blob/464aff88bed7c6b805a2397ef9c8f33de66be8b9/brax/physics/colliders.py#L518

So with the per-body friction/restitution scenario, I'll want to add the friction coefficients into a shared number instead? E.g. in box-plane collision, `friction = friction(box) + friction(plane)` and apply that to L518 above.

**Comment by flobotics** [comment]
hi,
you probably know it already and/or it is not directly related to this issue, but at least a nice video :) 

https://www.youtube.com/watch?v=CfJ074h9K8s
