### ISSUE TITLE
Training notebook not working due to JAX updates

### ISSUE THREAD

**Issue by peilundai** [google/brax#64]
JAX pushed a new updates yesterday after which the Brax training script doesn't work anymore with the following message. I am not sure if the Brax side could help resolve the issue or we need help from JAX team. 

<img width="1367" alt="Screenshot 2021-09-24 at 11 54 13 AM" src="https://user-images.githubusercontent.com/7687089/134616028-5f520790-6c1e-44fb-be75-5d03ef069a2f.png">

**Comment by erikfrey** [comment]
Hello!  Thanks for pointing this out.  JAX pushed a fix in 0.2.21.  This version is not yet bundled by default in colab, so you still need to run `pip update -U jax` at the top of the notebook for it to work.  I've updated the training notebook with this temporary fix - please let me know if that works for you.

**Comment by peilundai** [comment]
Thank you. It works now following the JAX update.
