### ISSUE TITLE
From pixels?

### ISSUE THREAD

**Issue by slerman12** [google/brax#67]
Is there a way to get the states as image frames?

**Comment by erikfrey** [comment]
Hi Sam,

We're pushing an update with support for rendering states on Tuesday or Wednesday.  Stay tuned!

**Comment by erikfrey** [comment]
OK, rendering to pixels is now available, but not yet documented.  If you'd like to try it, please check out:

https://github.com/google/brax/blob/main/brax/io/image.py

In the coming days we'll update our colabs with an example of how to use it.

**Comment by erikfrey** [comment]
Closing this as I think it's addressed, but please do re-open if you have any other questions.  We are tracking the request to render using accelerators at #108
