### ISSUE TITLE
Easiest way to port MuJoCo to Brax?

### ISSUE THREAD

**Issue by slerman12** [google/brax#68]
The code just relies on dm_control and dm_env packages. Are there any analogous Brax packages that I can use to port the code?

**Comment by cdfreeman-google** [comment]
We currently support conversion of (a small subset) of MuJoCo xml into brax configs via our converter tool here: https://github.com/google/brax/blob/main/brax/tools/mujoco_converter.py

You will have to manually tune some constants that don't have a good representation on the MuJoCo side, but are required on the brax side (like spring stiffnesses and damping parameters).  Let me know if you run into any trouble with the converter---it can be a little tricky to tune things correctly.

**Comment by erikfrey** [comment]
Closing this as I think it's addressed, but please do re-open if you have any other questions.

**Comment by benelot** [comment]
@erikfrey in case we would like to get more people to migrate from mujoco to brax, we should more openly document this somewhere I think. I found out about the mujoco_converter through discussions with the team and through this issue. If necessary, I can even provide a notebook in colab that helps with the migration of mujoco envs right in there.

**Comment by erikfrey** [comment]
@benelot good call, opened an issue to track this.
