### ISSUE TITLE
Differentiation through contact not working correctly

### ISSUE THREAD

**Issue by verityw** [google/brax#73]
I'm trying to do a simple example of differentiation through contact. I created a function that simulates a ball falling and bounding for 20 time steps. When I try taking the derivative of the final height with respect to the initial height, it always returns 1, even though it should not be a linear dependence. I've put together a example notebook demonstrating this, where I compute the aforementioned derivative numerically and analytically, and the two do not agree. I also plotted the numerical derivative as a function of starting height -- the derivative is only 1 when the ball is sufficiently high, but that's just because it does not hit the ground in 20 timesteps. Here's the notebook: https://colab.research.google.com/drive/1btgxkX640FTGysYmlWmmgG2BXMfPrx05?usp=sharing

Is differentiating through contacts bugged?

**Comment by cdfreeman-google** [comment]
Closing, but feel free to reopen if you think this issue is _not_ resolved by smaller `h`.
