### ISSUE TITLE
mimax.ipynb broken from deprecated math import in brax.experimental 

### ISSUE THREAD

**Issue by MandiZhao** [google/brax#76]
## Issue:
Possibly due to some changes in other places, the mimax colab notebook is broken:

![Screen Shot 2021-10-20 at 11 50 35 AM](https://user-images.githubusercontent.com/35449161/138153735-9deed1e2-7fd0-4f9b-8418-1efdcbf15c85.png)

## Proposed fix

I cloned the repo into colab runtime and go to the file `brax/experimental/composer/components/pro_ant.py` to manually change this line:

https://github.com/google/brax/blob/8b97a821d533fc1ad99a3445af30527215c38043/brax/experimental/composer/components/pro_ant.py#L21

to `from brax import math` 

then `pip install -e brax/.` and resolved the error.

**Comment by erikfrey** [comment]
Hi Mandi - thank you for finding this issue and proposing a fix!  We've gone ahead and incorporated it, and just pushed the fix to the repo.
