### ISSUE TITLE
Evaluation during training should be deterministic?

### ISSUE THREAD

**Issue by conglu1997** [google/brax#77]
https://github.com/google/brax/blob/8d80fa5d7127d374b73ac2b9d2ac36c990fd297f/brax/training/ppo.py#L288

The current evaluation during training is stochastic with actions being sampled, I think convention dictates we should take the mean? For example, the line could be replaced with:

```
            loc, _ = jnp.split(logits, 2, axis=-1)
            actions = parametric_action_distribution.postprocess(loc)
```

**Comment by erikfrey** [comment]
Closing this as I think it's addressed, but please do re-open if you have any other questions.
