### ISSUE TITLE
Are environments deterministic?

### ISSUE THREAD

**Issue by limbryan** [google/brax#80]
Hi,

I was wondering if the Brax Environments were deterministic. I have been trying to reproduce exact trajectories from the exact same policies after training but have been unable to do so. I have been using the composer methods to instantiate my environment. I see in the standard Ant environment, there is some sampling going on during resets (https://github.com/google/brax/blob/main/brax/envs/ant.py#L28) which perhaps may be the source of the stochasticity but do not see this in the composer environments. 

I have made sure that the policy is non-stochastic (i.e. no sampling from a distribution). Do you have any clues as to where the stochasticity might be coming from? Is there an easy way (an argument/flag) to ensure everything is deterministic and reproducible? 

Thanks!

**Comment by cdfreeman-google** [comment]
Slight correction for the sake of precision, XLA:GPU reductions are nondeterministic at the _software_ level, see https://github.com/google/jax/issues/565 for more details.

**Comment by erikfrey** [comment]
Closing this as I think it's addressed, but please do re-open if you have any other questions.
